# Generated by Django 5.0.6 on 2024-06-10 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageBoard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='messageBoard.user'),
        ),
    ]
